apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: acme
commonLabels:
  app: acme

configMapGenerator:
  - name: acme-scripts
    files: 
      - pre-script.sh
  - name: acme-envs
    env: local.env

secretGenerator:
  - name: acme
    env: secret.env

resources:
  - deployment.yml
  - auth.yml
  - pvc.yml