kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: acme
spec:
  storageClassName: cinder-classic
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Mi